version: '3.4'

services:
  basicdeploydigitalocean:
    image: basicdeploydigitalocean
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001