name: Node Github CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          mkdir ~/containers 
          cd ~/containers
          git clone https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}.git
          cd ${{ github.event.repository.name }}
          echo ${{github}}
          git pull origin ${{env.GITHUB_REF_NAME}}
          [ ! -f .env ] && ~/containers/set_incremental_port.sh # Cria o .env usando como modelo o que está no servidor
          docker-compose config
          docker-compose down --rmi all
          docker-compose up -d --no-deps --build
